import "../styles/reset.css";
import "../styles/globals.css";

import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mr.KARAHALİL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={inter.className} lang="tr">
      <body className="container ">
        <main>{children}</main>       
      </body>
    </html>
  );
}
